#!/usr/bin/env python
import json
import sys
import re

JUST_WHITESPACE = re.compile(r'^\s+$')
ENDS_WHITESPACE = re.compile(r'^.*([^\s]+)\s+$')

BEGINS_SPACES = re.compile(r'^\ +(.*)$')
BEGINS_TABS = re.compile(r'^\t+(.*)$')

data = json.loads(sys.stdin.read())
files = data['files']
config = data['config']

# This will hold our output
out = {}

for f in files:
    # Add a new key to our dictionary based on the filename
    out[f['name']] = []

    tabs = False
    spaces = False

    for line, kind, content in f['diff']:
        if kind == '-':
            # Skip lines that are removed
            continue

        if BEGINS_SPACES.search(content):
            spaces = True

        if BEGINS_TABS.search(content):
            tabs = True

        if JUST_WHITESPACE.search(content):
            out[f['name']].append(
                (line, 'warn', 'is nothing but whitespace'))

        if ENDS_WHITESPACE.search(content):
            out[f['name']].append(
                (line, 'warn', 'ends with whitespace'))


    if tabs and spaces:
        out[f['name']].append(
            ('warn', 'has a mix of tabs and spaces'))


# Finally, write to stdout the JSON encoded output
sys.stdout.write(json.dumps(out, indent=4))

# Tell Git that the plugin ran successfully (according to design)
exit(0)
